name: Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests
        
    - name: Build with Maven
      run: mvn -B package --file api-testing/rest-assured-framework/pom.xml
    
    - name: Run API Tests
      run: mvn test -Dtest=ApiTest
      working-directory: api-testing/rest-assured-framework
    
    - name: Generate Test Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: api-testing/rest-assured-framework/target/surefire-reports